### ISSUE TITLE
Nothing is displayed when evaling a form that uses the quote reader macro

### ISSUE THREAD

**Issue by kenny-evitt** [LightTable/Clojure#72]
This was reported initially (or at least most recently) in [this Google Groups topic](https://groups.google.com/d/topic/light-table-discussion/3YejenLOfho/discussion).

I confirmed this behavior in LT version 0.8.1 with version 0.3.1 of the Clojure plugin.

An example form:

```
'(+ 1 2 3 4 5)
```

Interestingly, `(quote (+ 1 2 3 4 5))`, when evaled, displays `(+ 1 2 3 4 5)`.

**Comment by rundis** [comment]
If you select the expression and try to eval you get a runtime exception (confirmed with 0.3.2)

```
Invalid behavior: :lt.objs.eval/inline-results
TypeError: Cannot read property 'addEventListener' of undefined
    at Function.CodeMirror.on (/Applications/LightTable.app/Contents/Resources/app/core/node_modules/codemirror/lib/codemirror.js:7101:16)
    at Function.<anonymous> (file:///Applications/LightTable.app/Contents/Resources/app/core/node_modules/lighttable/bootstrap.js:30923:16)
    at c (file:///Applications/LightTable.app/Contents/Resources/app/core/node_modules/lighttable/bootstrap.js:6196:14)
    at a (file:///Applications/LightTable.app/Contents/Resources/app/core/node_modules/lighttable/bootstrap.js:6236:18)
    at a (file:///Applications/LightTable.app/Contents/Resources/app/core/node_modules/lighttable/bootstrap.js:20652:136)
    at b (file:///Applications/LightTable.app/Contents/Resources/app/core/node_modules/lighttable/bootstrap.js:20664:14)
    at Function.lt.objs.eval.__BEH__inline_results
```

Same as https://github.com/LightTable/LightTable/issues/2162
