### ISSUE TITLE
Instarepl throws javascript error

### ISSUE THREAD

**Issue by frankadrian314159** [LightTable/Clojure#82]
Type :3 in a Clojure window and select it. Hit ctrl-enter to evaluate.

Expected result: The keyword :3 (Try it in a hash table - it works).

Actual result: Stack trace in console:
Invalid behavior: :lt.objs.eval/inline-results
TypeError: Cannot read property 'addEventListener' of undefined
    at Function.CodeMirror.on (C:%5Cbin%5Clighttable-0.8.1-windows%5Cresources%5Capp%5Ccore%5Cnode_modules%5Ccodemirror%5Clib%5Ccodemirror.js:7101:16)
    at Function.<anonymous> (file:///C:/bin/lighttable-0.8.1-windows/resources/app/core/node_modules/lighttable/bootstrap.js:30923:16)
    at c (file:///C:/bin/lighttable-0.8.1-windows/resources/app/core/node_modules/lighttable/bootstrap.js:6196:14)
    at a (file:///C:/bin/lighttable-0.8.1-windows/resources/app/core/node_modules/lighttable/bootstrap.js:6236:18)
    at a (file:///C:/bin/lighttable-0.8.1-windows/resources/app/core/node_modules/lighttable/bootstrap.js:20652:136)
    at b (file:///C:/bin/lighttable-0.8.1-windows/resources/app/core/node_modules/lighttable/bootstrap.js:20664:14)
    at Function.lt.objs.eval.__BEH__inline_results (file:///C:/bin/lighttable-0.8.1-windows/resources/app/core/node_modules/lighttable/bootstrap.js:30936:24)
    at c (file:///C:/bin/lighttable-0.8.1-windows/resources/app/core/node_modules/lighttable/bootstrap.js:6196:14)
    at a (file:///C:/bin/lighttable-0.8.1-windows/resources/app/core/node_modules/lighttable/bootstrap.js:6236:18)
    at c (file:///C:/bin/lighttable-0.8.1-windows/resources/app/core/node_modules/lighttable/bootstrap.js:20339:76)

**Comment by carocad** [comment]
@frankadrian314159 thanks for the report. I think this is not related to instarepl but to the Clojure plugin itself. There seems to be a bug with the custom-evaluation (selection and evaling) as reported in #72 and #81
